"""Added reviews to rating

Revision ID: 20f7d3b0b9f1
Revises: 6acfb1c30cdc
Create Date: 2025-09-18 08:34:49.081084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f7d3b0b9f1'
down_revision: Union[str, Sequence[str], None] = '6acfb1c30cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('review', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'review')
    # ### end Alembic commands ###
