"""Index on Genre

Revision ID: 6acfb1c30cdc
Revises: 9109f29273fd
Create Date: 2025-07-21 09:25:42.141221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acfb1c30cdc'
down_revision: Union[str, Sequence[str], None] = '9109f29273fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_gender_name', 'genre', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gender_name', table_name='genre')
    # ### end Alembic commands ###
